<?php
/**
 * @package Linguator
 */
namespace Linguator\Settings\Controllers;
if ( ! defined( 'ABSPATH' ) ) {
	exit; // Don't access directly
}

/**
 * The list of flags
 *
 * For each flag:
 * the key is the flag file name (without the extension)
 * the value is the Country name
 */
// phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound
$flags = array(
	'ad'        => __( 'Andorra', 'linguator-multilingual-ai-translation' ),
	'ae'        => __( 'United Arab Emirates', 'linguator-multilingual-ai-translation' ),
	'af'        => __( 'Afghanistan', 'linguator-multilingual-ai-translation' ),
	'ag'        => __( 'Antigua and Barbuda', 'linguator-multilingual-ai-translation' ),
	'ai'        => __( 'Anguilla', 'linguator-multilingual-ai-translation' ),
	'al'        => __( 'Albania', 'linguator-multilingual-ai-translation' ),
	'am'        => __( 'Armenia', 'linguator-multilingual-ai-translation' ),
	'an'        => __( 'Netherlands Antilles', 'linguator-multilingual-ai-translation' ),
	'ao'        => __( 'Angola', 'linguator-multilingual-ai-translation' ),
	'ar'        => __( 'Argentina', 'linguator-multilingual-ai-translation' ),
	'arab'      => __( 'Arab league', 'linguator-multilingual-ai-translation' ),
	'as'        => __( 'American Samoa', 'linguator-multilingual-ai-translation' ),
	'at'        => __( 'Austria', 'linguator-multilingual-ai-translation' ),
	'au'        => __( 'Australia', 'linguator-multilingual-ai-translation' ),
	'aw'        => __( 'Aruba', 'linguator-multilingual-ai-translation' ),
	'ax'        => __( 'Åland Islands', 'linguator-multilingual-ai-translation' ),
	'az'        => __( 'Azerbaijan', 'linguator-multilingual-ai-translation' ),
	'ba'        => __( 'Bosnia and Herzegovina', 'linguator-multilingual-ai-translation' ),
	'basque'    => __( 'Basque Country', 'linguator-multilingual-ai-translation' ),
	'bb'        => __( 'Barbados', 'linguator-multilingual-ai-translation' ),
	'bd'        => __( 'Bangladesh', 'linguator-multilingual-ai-translation' ),
	'be'        => __( 'Belgium', 'linguator-multilingual-ai-translation' ),
	'bf'        => __( 'Burkina Faso', 'linguator-multilingual-ai-translation' ),
	'bg'        => __( 'Bulgaria', 'linguator-multilingual-ai-translation' ),
	'bh'        => __( 'Bahrain', 'linguator-multilingual-ai-translation' ),
	'bi'        => __( 'Burundi', 'linguator-multilingual-ai-translation' ),
	'bj'        => __( 'Benin', 'linguator-multilingual-ai-translation' ),
	'bm'        => __( 'Bermuda', 'linguator-multilingual-ai-translation' ),
	'bn'        => __( 'Brunei', 'linguator-multilingual-ai-translation' ),
	'bo'        => __( 'Bolivia', 'linguator-multilingual-ai-translation' ),
	'br'        => __( 'Brazil', 'linguator-multilingual-ai-translation' ),
	'bs'        => __( 'Bahamas', 'linguator-multilingual-ai-translation' ),
	'bt'        => __( 'Bhutan', 'linguator-multilingual-ai-translation' ),
	'bw'        => __( 'Botswana', 'linguator-multilingual-ai-translation' ),
	'by'        => __( 'Belarus', 'linguator-multilingual-ai-translation' ),
	'bz'        => __( 'Belize', 'linguator-multilingual-ai-translation' ),
	'ca'        => __( 'Canada', 'linguator-multilingual-ai-translation' ),
	'catalonia' => __( 'Catalonia', 'linguator-multilingual-ai-translation' ),
	'cc'        => __( 'Cocos', 'linguator-multilingual-ai-translation' ),
	'cd'        => __( 'Democratic Republic of the Congo', 'linguator-multilingual-ai-translation' ),
	'cf'        => __( 'Central African Republic', 'linguator-multilingual-ai-translation' ),
	'cg'        => __( 'Congo', 'linguator-multilingual-ai-translation' ),
	'ch'        => __( 'Switzerland', 'linguator-multilingual-ai-translation' ),
	'ci'        => __( 'Ivory Coast', 'linguator-multilingual-ai-translation' ),
	'ck'        => __( 'Cook Islands', 'linguator-multilingual-ai-translation' ),
	'cl'        => __( 'Chile', 'linguator-multilingual-ai-translation' ),
	'cm'        => __( 'Cameroon', 'linguator-multilingual-ai-translation' ),
	'cn'        => __( 'China', 'linguator-multilingual-ai-translation' ),
	'co'        => __( 'Colombia', 'linguator-multilingual-ai-translation' ),
	'cr'        => __( 'Costa Rica', 'linguator-multilingual-ai-translation' ),
	'cu'        => __( 'Cuba', 'linguator-multilingual-ai-translation' ),
	'cv'        => __( 'Cape Verde', 'linguator-multilingual-ai-translation' ),
	'cx'        => __( 'Christmas Island', 'linguator-multilingual-ai-translation' ),
	'cy'        => __( 'Cyprus', 'linguator-multilingual-ai-translation' ),
	'cz'        => __( 'Czech Republic', 'linguator-multilingual-ai-translation' ),
	'de'        => __( 'Germany', 'linguator-multilingual-ai-translation' ),
	'dj'        => __( 'Djibouti', 'linguator-multilingual-ai-translation' ),
	'dk'        => __( 'Denmark', 'linguator-multilingual-ai-translation' ),
	'dm'        => __( 'Dominica', 'linguator-multilingual-ai-translation' ),
	'do'        => __( 'Dominican Republic', 'linguator-multilingual-ai-translation' ),
	'dz'        => __( 'Algeria', 'linguator-multilingual-ai-translation' ),
	'ec'        => __( 'Ecuador', 'linguator-multilingual-ai-translation' ),
	'ee'        => __( 'Estonia', 'linguator-multilingual-ai-translation' ),
	'eg'        => __( 'Egypt', 'linguator-multilingual-ai-translation' ),
	'eh'        => __( 'Western Sahara', 'linguator-multilingual-ai-translation' ),
	'england'   => __( 'England', 'linguator-multilingual-ai-translation' ),
	'er'        => __( 'Eritrea', 'linguator-multilingual-ai-translation' ),
	'es'        => __( 'Spain', 'linguator-multilingual-ai-translation' ),
	'esperanto' => __( 'Esperanto', 'linguator-multilingual-ai-translation' ),
	'et'        => __( 'Ethiopia', 'linguator-multilingual-ai-translation' ),
	'fi'        => __( 'Finland', 'linguator-multilingual-ai-translation' ),
	'fj'        => __( 'Fiji', 'linguator-multilingual-ai-translation' ),
	'fk'        => __( 'Falkland Islands', 'linguator-multilingual-ai-translation' ),
	'fm'        => __( 'Micronesia', 'linguator-multilingual-ai-translation' ),
	'fo'        => __( 'Faroe Islands', 'linguator-multilingual-ai-translation' ),
	'fr'        => __( 'France', 'linguator-multilingual-ai-translation' ),
	'ga'        => __( 'Gabon', 'linguator-multilingual-ai-translation' ),
	'galicia'   => __( 'Galicia', 'linguator-multilingual-ai-translation' ),
	'gb'        => __( 'United Kingdom', 'linguator-multilingual-ai-translation' ),
	'gd'        => __( 'Grenada', 'linguator-multilingual-ai-translation' ),
	'ge'        => __( 'Georgia', 'linguator-multilingual-ai-translation' ),
	'gh'        => __( 'Ghana', 'linguator-multilingual-ai-translation' ),
	'gi'        => __( 'Gibraltar', 'linguator-multilingual-ai-translation' ),
	'gl'        => __( 'Greenland', 'linguator-multilingual-ai-translation' ),
	'gm'        => __( 'Gambia', 'linguator-multilingual-ai-translation' ),
	'gn'        => __( 'Guinea', 'linguator-multilingual-ai-translation' ),
	'gp'        => __( 'Guadeloupe', 'linguator-multilingual-ai-translation' ),
	'gq'        => __( 'Equatorial Guinea', 'linguator-multilingual-ai-translation' ),
	'gr'        => __( 'Greece', 'linguator-multilingual-ai-translation' ),
	'gs'        => __( 'South Georgia and the South Sandwich Islands', 'linguator-multilingual-ai-translation' ),
	'gt'        => __( 'Guatemala', 'linguator-multilingual-ai-translation' ),
	'gu'        => __( 'Guam', 'linguator-multilingual-ai-translation' ),
	'gw'        => __( 'Guinea-Bissau', 'linguator-multilingual-ai-translation' ),
	'gy'        => __( 'Guyana', 'linguator-multilingual-ai-translation' ),
	'hk'        => __( 'Hong Kong', 'linguator-multilingual-ai-translation' ),
	'hm'        => __( 'Heard Island and McDonald Islands', 'linguator-multilingual-ai-translation' ),
	'hn'        => __( 'Honduras', 'linguator-multilingual-ai-translation' ),
	'hr'        => __( 'Croatia', 'linguator-multilingual-ai-translation' ),
	'ht'        => __( 'Haiti', 'linguator-multilingual-ai-translation' ),
	'hu'        => __( 'Hungary', 'linguator-multilingual-ai-translation' ),
	'id'        => __( 'Indonesia', 'linguator-multilingual-ai-translation' ),
	'ie'        => __( 'Republic of Ireland', 'linguator-multilingual-ai-translation' ),
	'il'        => __( 'Israel', 'linguator-multilingual-ai-translation' ),
	'in'        => __( 'India', 'linguator-multilingual-ai-translation' ),
	'io'        => __( 'British Indian Ocean Territory', 'linguator-multilingual-ai-translation' ),
	'iq'        => __( 'Iraq', 'linguator-multilingual-ai-translation' ),
	'ir'        => __( 'Iran', 'linguator-multilingual-ai-translation' ),
	'is'        => __( 'Iceland', 'linguator-multilingual-ai-translation' ),
	'it'        => __( 'Italy', 'linguator-multilingual-ai-translation' ),
	'jm'        => __( 'Jamaica', 'linguator-multilingual-ai-translation' ),
	'jo'        => __( 'Jordan', 'linguator-multilingual-ai-translation' ),
	'jp'        => __( 'Japan', 'linguator-multilingual-ai-translation' ),
	'ke'        => __( 'Kenya', 'linguator-multilingual-ai-translation' ),
	'kg'        => __( 'Kyrgyzstan', 'linguator-multilingual-ai-translation' ),
	'kh'        => __( 'Cambodia', 'linguator-multilingual-ai-translation' ),
	'ki'        => __( 'Kiribati', 'linguator-multilingual-ai-translation' ),
	'km'        => __( 'Comoros', 'linguator-multilingual-ai-translation' ),
	'kn'        => __( 'Saint Kitts and Nevis', 'linguator-multilingual-ai-translation' ),
	'kp'        => __( 'North Korea', 'linguator-multilingual-ai-translation' ),
	'kr'        => __( 'South Korea', 'linguator-multilingual-ai-translation' ),
	'kurdistan' => __( 'Kurdistan', 'linguator-multilingual-ai-translation' ),
	'kw'        => __( 'Kuwait', 'linguator-multilingual-ai-translation' ),
	'ky'        => __( 'Cayman Islands', 'linguator-multilingual-ai-translation' ),
	'kz'        => __( 'Kazakhstan', 'linguator-multilingual-ai-translation' ),
	'la'        => __( 'Laos', 'linguator-multilingual-ai-translation' ),
	'lb'        => __( 'Lebanon', 'linguator-multilingual-ai-translation' ),
	'lc'        => __( 'Saint Lucia', 'linguator-multilingual-ai-translation' ),
	'li'        => __( 'Liechtenstein', 'linguator-multilingual-ai-translation' ),
	'lk'        => __( 'Sri Lanka', 'linguator-multilingual-ai-translation' ),
	'lr'        => __( 'Liberia', 'linguator-multilingual-ai-translation' ),
	'ls'        => __( 'Lesotho', 'linguator-multilingual-ai-translation' ),
	'lt'        => __( 'Lithuania', 'linguator-multilingual-ai-translation' ),
	'lu'        => __( 'Luxembourg', 'linguator-multilingual-ai-translation' ),
	'lv'        => __( 'Latvia', 'linguator-multilingual-ai-translation' ),
	'ly'        => __( 'Libya', 'linguator-multilingual-ai-translation' ),
	'ma'        => __( 'Morocco', 'linguator-multilingual-ai-translation' ),
	'mc'        => __( 'Monaco', 'linguator-multilingual-ai-translation' ),
	'md'        => __( 'Moldova', 'linguator-multilingual-ai-translation' ),
	'me'        => __( 'Montenegro', 'linguator-multilingual-ai-translation' ),
	'mg'        => __( 'Madagascar', 'linguator-multilingual-ai-translation' ),
	'mh'        => __( 'Marshall Islands', 'linguator-multilingual-ai-translation' ),
	'mk'        => __( 'North Macedonia', 'linguator-multilingual-ai-translation' ),
	'ml'        => __( 'Mali', 'linguator-multilingual-ai-translation' ),
	'mm'        => __( 'Myanmar', 'linguator-multilingual-ai-translation' ),
	'mn'        => __( 'Mongolia', 'linguator-multilingual-ai-translation' ),
	'mo'        => __( 'Macao', 'linguator-multilingual-ai-translation' ),
	'mp'        => __( 'Northern Mariana Islands', 'linguator-multilingual-ai-translation' ),
	'mq'        => __( 'Martinique', 'linguator-multilingual-ai-translation' ),
	'mr'        => __( 'Mauritania', 'linguator-multilingual-ai-translation' ),
	'ms'        => __( 'Montserrat', 'linguator-multilingual-ai-translation' ),
	'mt'        => __( 'Malta', 'linguator-multilingual-ai-translation' ),
	'mu'        => __( 'Mauritius', 'linguator-multilingual-ai-translation' ),
	'mv'        => __( 'Maldives', 'linguator-multilingual-ai-translation' ),
	'mw'        => __( 'Malawi', 'linguator-multilingual-ai-translation' ),
	'mx'        => __( 'Mexico', 'linguator-multilingual-ai-translation' ),
	'my'        => __( 'Malaysia', 'linguator-multilingual-ai-translation' ),
	'mz'        => __( 'Mozambique', 'linguator-multilingual-ai-translation' ),
	'na'        => __( 'Namibia', 'linguator-multilingual-ai-translation' ),
	'nc'        => __( 'New Caledonia', 'linguator-multilingual-ai-translation' ),
	'ne'        => __( 'Niger', 'linguator-multilingual-ai-translation' ),
	'nf'        => __( 'Norfolk Island', 'linguator-multilingual-ai-translation' ),
	'ng'        => __( 'Nigeria', 'linguator-multilingual-ai-translation' ),
	'ni'        => __( 'Nicaragua', 'linguator-multilingual-ai-translation' ),
	'nl'        => __( 'Netherlands', 'linguator-multilingual-ai-translation' ),
	'no'        => __( 'Norway', 'linguator-multilingual-ai-translation' ),
	'np'        => __( 'Nepal', 'linguator-multilingual-ai-translation' ),
	'nr'        => __( 'Nauru', 'linguator-multilingual-ai-translation' ),
	'nu'        => __( 'Niue', 'linguator-multilingual-ai-translation' ),
	'nz'        => __( 'New Zealand', 'linguator-multilingual-ai-translation' ),
	'occitania' => __( 'Occitania', 'linguator-multilingual-ai-translation' ),
	'om'        => __( 'Oman', 'linguator-multilingual-ai-translation' ),
	'pa'        => __( 'Panama', 'linguator-multilingual-ai-translation' ),
	'pe'        => __( 'Peru', 'linguator-multilingual-ai-translation' ),
	'pf'        => __( 'French Polynesia', 'linguator-multilingual-ai-translation' ),
	'pg'        => __( 'Papua New Guinea', 'linguator-multilingual-ai-translation' ),
	'ph'        => __( 'Philippines', 'linguator-multilingual-ai-translation' ),
	'pk'        => __( 'Pakistan', 'linguator-multilingual-ai-translation' ),
	'pl'        => __( 'Poland', 'linguator-multilingual-ai-translation' ),
	'pm'        => __( 'Saint Pierre and Miquelon', 'linguator-multilingual-ai-translation' ),
	'pn'        => __( 'Pitcairn', 'linguator-multilingual-ai-translation' ),
	'pr'        => __( 'Puerto Rico', 'linguator-multilingual-ai-translation' ),
	'ps'        => __( 'Palestinian Territory', 'linguator-multilingual-ai-translation' ),
	'pt'        => __( 'Portugal', 'linguator-multilingual-ai-translation' ),
	'pw'        => __( 'Belau', 'linguator-multilingual-ai-translation' ),
	'py'        => __( 'Paraguay', 'linguator-multilingual-ai-translation' ),
	'qa'        => __( 'Qatar', 'linguator-multilingual-ai-translation' ),
	'quebec'    => __( 'Quebec', 'linguator-multilingual-ai-translation' ),
	'ro'        => __( 'Romania', 'linguator-multilingual-ai-translation' ),
	'rs'        => __( 'Serbia', 'linguator-multilingual-ai-translation' ),
	'ru'        => __( 'Russia', 'linguator-multilingual-ai-translation' ),
	'rw'        => __( 'Rwanda', 'linguator-multilingual-ai-translation' ),
	'sa'        => __( 'Saudi Arabia', 'linguator-multilingual-ai-translation' ),
	'sb'        => __( 'Solomon Islands', 'linguator-multilingual-ai-translation' ),
	'sc'        => __( 'Seychelles', 'linguator-multilingual-ai-translation' ),
	'scotland'  => __( 'Scotland', 'linguator-multilingual-ai-translation' ),
	'sd'        => __( 'Sudan', 'linguator-multilingual-ai-translation' ),
	'se'        => __( 'Sweden', 'linguator-multilingual-ai-translation' ),
	'sg'        => __( 'Singapore', 'linguator-multilingual-ai-translation' ),
	'sh'        => __( 'Saint Helena', 'linguator-multilingual-ai-translation' ),
	'si'        => __( 'Slovenia', 'linguator-multilingual-ai-translation' ),
	'sk'        => __( 'Slovakia', 'linguator-multilingual-ai-translation' ),
	'sl'        => __( 'Sierra Leone', 'linguator-multilingual-ai-translation' ),
	'sm'        => __( 'San Marino', 'linguator-multilingual-ai-translation' ),
	'sn'        => __( 'Senegal', 'linguator-multilingual-ai-translation' ),
	'so'        => __( 'Somalia', 'linguator-multilingual-ai-translation' ),
	'sr'        => __( 'Suriname', 'linguator-multilingual-ai-translation' ),
	'ss'        => __( 'South Sudan', 'linguator-multilingual-ai-translation' ),
	'st'        => __( 'São Tomé and Príncipe', 'linguator-multilingual-ai-translation' ),
	'sv'        => __( 'El Salvador', 'linguator-multilingual-ai-translation' ),
	'sy'        => __( 'Syria', 'linguator-multilingual-ai-translation' ),
	'sz'        => __( 'Swaziland', 'linguator-multilingual-ai-translation' ),
	'tc'        => __( 'Turks and Caicos Islands', 'linguator-multilingual-ai-translation' ),
	'td'        => __( 'Chad', 'linguator-multilingual-ai-translation' ),
	'tf'        => __( 'French Southern Territories', 'linguator-multilingual-ai-translation' ),
	'tg'        => __( 'Togo', 'linguator-multilingual-ai-translation' ),
	'th'        => __( 'Thailand', 'linguator-multilingual-ai-translation' ),
	'tibet'     => __( 'Tibet', 'linguator-multilingual-ai-translation' ),
	'tj'        => __( 'Tajikistan', 'linguator-multilingual-ai-translation' ),
	'tk'        => __( 'Tokelau', 'linguator-multilingual-ai-translation' ),
	'tl'        => __( 'Timor-Leste', 'linguator-multilingual-ai-translation' ),
	'tm'        => __( 'Turkmenistan', 'linguator-multilingual-ai-translation' ),
	'tn'        => __( 'Tunisia', 'linguator-multilingual-ai-translation' ),
	'to'        => __( 'Tonga', 'linguator-multilingual-ai-translation' ),
	'tr'        => __( 'Turkey', 'linguator-multilingual-ai-translation' ),
	'tt'        => __( 'Trinidad and Tobago', 'linguator-multilingual-ai-translation' ),
	'tv'        => __( 'Tuvalu', 'linguator-multilingual-ai-translation' ),
	'tw'        => __( 'Taiwan', 'linguator-multilingual-ai-translation' ),
	'tz'        => __( 'Tanzania', 'linguator-multilingual-ai-translation' ),
	'ua'        => __( 'Ukraine', 'linguator-multilingual-ai-translation' ),
	'ug'        => __( 'Uganda', 'linguator-multilingual-ai-translation' ),
	'us'        => __( 'United States', 'linguator-multilingual-ai-translation' ),
	'uy'        => __( 'Uruguay', 'linguator-multilingual-ai-translation' ),
	'uz'        => __( 'Uzbekistan', 'linguator-multilingual-ai-translation' ),
	'va'        => __( 'Vatican', 'linguator-multilingual-ai-translation' ),
	'vc'        => __( 'Saint Vincent and the Grenadines', 'linguator-multilingual-ai-translation' ),
	've'        => __( 'Venezuela', 'linguator-multilingual-ai-translation' ),
	'veneto'    => __( 'Veneto', 'linguator-multilingual-ai-translation' ),
	'vg'        => __( 'British Virgin Islands', 'linguator-multilingual-ai-translation' ),
	'vi'        => __( 'United States Virgin Islands', 'linguator-multilingual-ai-translation' ),
	'vn'        => __( 'Vietnam', 'linguator-multilingual-ai-translation' ),
	'vu'        => __( 'Vanuatu', 'linguator-multilingual-ai-translation' ),
	'wales'     => __( 'Wales', 'linguator-multilingual-ai-translation' ),
	'wf'        => __( 'Wallis and Futuna', 'linguator-multilingual-ai-translation' ),
	'ws'        => __( 'Western Samoa', 'linguator-multilingual-ai-translation' ),
	'ye'        => __( 'Yemen', 'linguator-multilingual-ai-translation' ),
	'yt'        => __( 'Mayotte', 'linguator-multilingual-ai-translation' ),
	'za'        => __( 'South Africa', 'linguator-multilingual-ai-translation' ),
	'zm'        => __( 'Zambia', 'linguator-multilingual-ai-translation' ),
	'zw'        => __( 'Zimbabwe', 'linguator-multilingual-ai-translation' ),
);

/**
 * Filter the list of predefined flags
 *
 *  
 *
 * @param array $flags
 */
return apply_filters( 'lmat_predefined_flags', $flags );
